language: java
jdk:
  - oraclejdk7
before_install:
  - wget -O dafny-1.9.7.zip "http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=dafny&DownloadId=1559952&FileTime=131040300896400000&Build=21031"
  - unzip dafny-1.9.7.zip
script:
  - ant main
